"use client";

import LegalLayout from "./LegalLayout";

export default function AIAddendumPage() {
  return (
    <LegalLayout activePage="/legal/ai-addendum/">
      <div className="flex items-center justify-between mb-6">
        <h2 className="font-inter text-xl font-semibold text-black">AI services addendum</h2>
        <span className="text-xs text-gray-400">Last updated: September 15, 2025</span>
      </div>
      <div className="prose prose-sm max-w-none text-gray-700 leading-relaxed space-y-5">
        <p>This AI Addendum integrates into Plivo&apos;s Terms of Service, Service Schedule, or primary agreement and governs access to and use of AI Features.</p>

        <h3 className="font-inter text-base font-semibold text-black mt-6 mb-2">1. Definitions</h3>
        <ul className="list-disc pl-5 space-y-2">
          <li><strong>AI Agent:</strong> A specific instance of an AI Feature developed by Customer or provided by Plivo, configured to perform tasks, engage in conversations, or automate workflows.</li>
          <li><strong>AI Features/AI Services:</strong> Services enabling data analysis to identify patterns, make predictions, and generate content using machine learning, including Predictive Analytics, NLP, Computer Vision, Generative AI, Speech Recognition and Synthesis.</li>
          <li><strong>Input:</strong> All data, prompts, queries, files, or content submitted by Customer to AI Features.</li>
          <li><strong>Output:</strong> All text, code, images, or content generated by AI Features in response to Input.</li>
          <li><strong>Connectors:</strong> Features including plugins and actions allowing AI Services to interact with third-party applications.</li>
        </ul>

        <h3 className="font-inter text-base font-semibold text-black mt-6 mb-2">2. Rights grant</h3>
        <p>Plivo retains all rights to AI Services, granting Customer a non-exclusive, non-transferable right to access and use AI Features for internal business purposes.</p>

        <h3 className="font-inter text-base font-semibold text-black mt-6 mb-2">3. Use of AI agents</h3>
        <p>AI Services allow Customer to develop, configure, and deploy AI Agents, with pre-built options available. AI Agent behavior depends on Customer&apos;s specific use case and configuration; Plivo functions as an enabling platform.</p>
        <p className="font-semibold text-gray-900">Plivo shall not be responsible for, and expressly disclaims all liability for, any and all actions, decisions, or outputs made by an AI Agent created, configured, or used by you or at your direction.</p>

        <h3 className="font-inter text-base font-semibold text-black mt-6 mb-2">4. Connectors and third-party applications</h3>
        <p>Customer is solely responsible for actions using Connectors. Customer controls whether Connectors are enabled. When enabled, Customer authorizes AI Services to send data to third-party applications per their terms and privacy policies. Content retrieved may be included in Output.</p>

        <h3 className="font-inter text-base font-semibold text-black mt-6 mb-2">5. Third-party providers</h3>
        <p>AI Features are powered by third-party providers. Using AI Features constitutes acknowledgment of and agreement to applicable Third-Party Terms, including obligations, restrictions, and disclaimers.</p>

        <h3 className="font-inter text-base font-semibold text-black mt-6 mb-2">6. Customer responsibilities</h3>
        <ul className="list-disc pl-5 space-y-2">
          <li><strong>Content:</strong> Customer is solely responsible for all Input provided and warrants having necessary rights and permissions.</li>
          <li><strong>Output Validation:</strong> Output is generated by experimental technology and may be inaccurate. Customer is solely responsible for reviewing and validating all Output before use.</li>
          <li><strong>Sensitive Information:</strong> Customer must not provide sensitive personal data or PHI unless a separate BAA is executed.</li>
          <li><strong>End User Disclosures:</strong> Customer must inform end users they are interacting with AI, that conversations are recorded, and must obtain necessary consents including TCPA compliance for outbound calls.</li>
          <li><strong>Indemnification:</strong> Customer agrees to indemnify Plivo from claims arising from AI Agent use, outputs, applicable law breaches, and this Addendum.</li>
        </ul>

        <h3 className="font-inter text-base font-semibold text-black mt-6 mb-2">7. Intellectual property</h3>
        <ul className="list-disc pl-5 space-y-2">
          <li><strong>Input:</strong> Customer retains all ownership rights.</li>
          <li><strong>Output:</strong> Customer owns the Output. Plivo assigns all right, title, and interest to Customer.</li>
          <li><strong>Similar Content:</strong> Due to machine learning&apos;s nature, Output may not be unique; other users may receive similar outputs.</li>
          <li><strong>Feedback:</strong> Customer grants Plivo a worldwide, perpetual, royalty-free license to use any feedback.</li>
          <li><strong>Service Improvement:</strong> Customer grants Plivo a license to use anonymized and aggregated Input/Output data for service improvement.</li>
        </ul>

        <h3 className="font-inter text-base font-semibold text-black mt-6 mb-2">8. Acceptable use</h3>
        <p>Customer will not:</p>
        <ul className="list-disc pl-5 space-y-2">
          <li>Use AI Features to develop competing AI/ML models</li>
          <li>Represent Output as wholly human-generated work</li>
          <li>Use AI for automated high-stakes decisions (credit, employment, housing, legal, medical) without human review</li>
          <li>Use AI for illegal, fraudulent, deceptive, or harmful purposes</li>
          <li>Reverse engineer or extract models/source code from AI Features</li>
        </ul>

        <h3 className="font-inter text-base font-semibold text-black mt-6 mb-2">9. Third-party providers (Exhibit A)</h3>
        <p>Current AI providers include:</p>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-200">
                <th className="py-2.5 pr-4 text-left font-semibold text-black">Provider</th>
                <th className="py-2.5 text-left font-semibold text-black">Service</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {[
                ["Claude (Anthropic)", "AI/LLM"],
                ["Google LLC (Vertex)", "AI/LLM"],
                ["OpenAI", "AI/LLM"],
                ["Deepgram", "Transcription"],
                ["ElevenLabs", "Audio generation"],
                ["Cartesia", "Audio generation"],
                ["Groq Inc.", "AI inference"],
                ["Perplexity", "AI search"],
                ["Sarvam AI", "AI/LLM"],
                ["MS Azure", "AI infrastructure"],
              ].map(([provider, service]) => (
                <tr key={provider}>
                  <td className="py-2.5 pr-4 font-medium text-gray-900">{provider}</td>
                  <td className="py-2.5 text-gray-600">{service}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="mt-8 pt-6 border-t border-gray-200">
          <p className="text-xs text-gray-400">
            For the complete AI Services Addendum, please visit{" "}
            <a href="https://www.plivo.com/legal/service-schedule/artificial-intelligence-services-addendum/" target="_blank" rel="noopener noreferrer" className="text-[#323dfe] hover:underline">plivo.com/legal/ai-services-addendum</a>.
          </p>
        </div>
      </div>
    </LegalLayout>
  );
}
