"use client";

import LegalLayout from "./LegalLayout";

export default function ServicesSchedulePage() {
  return (
    <LegalLayout activePage="/legal/services-schedule/">
      <div className="flex items-center justify-between mb-6">
        <h2 className="font-sora text-xl font-medium text-black">Services schedule</h2>
        <span className="text-xs text-gray-400">Last updated: January 27, 2025</span>
      </div>
      <div className="prose prose-sm max-w-none text-gray-700 leading-relaxed space-y-5">
        <h3 className="font-inter text-base font-semibold text-black mt-6 mb-2">1. Updates to services</h3>
        <p>Plivo may update, upgrade or modify the Services, provided the updates do not result in a material reduction of functionality, performance, availability, or security. Plivo provides notice before discontinuing services, unless replaced with materially similar functionality. No limitations apply to changes required for legal compliance, security risks, or new pre-release service features.</p>

        <h3 className="font-inter text-base font-semibold text-black mt-6 mb-2">2. Support packages and service levels</h3>
        <p>Support services follow applicable support packages and service levels per the Services Support documentation.</p>

        <h3 className="font-inter text-base font-semibold text-black mt-6 mb-2">3. Customer account</h3>
        <p>Customers must provide accurate information. False information may result in account suspension or service termination.</p>

        <h3 className="font-inter text-base font-semibold text-black mt-6 mb-2">4. Consents and permissions</h3>
        <p>Customers are solely responsible for obtaining necessary permissions and consents from end users to receive messages, including compliance with state laws and the Telephone Consumer Protection Act. Customers must notify users they can opt out via STOP, END, CANCEL, UNSUBSCRIBE, or QUIT.</p>

        <h3 className="font-inter text-base font-semibold text-black mt-6 mb-2">5. Content</h3>
        <p>Customers retain rights to content submitted. Customers are responsible for applications, data, and traffic originating from their accounts. Authentication keys and credentials are the customer&apos;s responsibility.</p>

        <h3 className="font-inter text-base font-semibold text-black mt-6 mb-2">6. Customer applications</h3>
        <p>Customers warrant they own applications, have necessary rights and licenses, and that content does not violate laws or third-party rights. Customers are responsible for charges incurred through their applications.</p>

        <h3 className="font-inter text-base font-semibold text-black mt-6 mb-2">7. Third party services</h3>
        <p>Third-party service terms apply separately. Plivo is not responsible for third-party performance, functionality, security, or data handling. Customers assume all risks from third-party service use.</p>
        <p>Plivo may utilize artificial intelligence and machine learning technologies to enhance services. Customers are solely responsible for obtaining necessary consents for AI/ML technology use and data sharing.</p>
        <p>AI/ML outputs may be incorrect or incomplete. Customers agree to independently review, verify, and validate all outputs generated by AI/ML technologies before relying on them. Customers must not provide personally identifiable information or personal health information.</p>
        <p>WhatsApp Business Solution users must also comply with <a href="/legal/supplemental/" className="text-[#323dfe] hover:underline">supplemental terms</a>.</p>

        <h3 className="font-inter text-base font-semibold text-black mt-6 mb-2">8. Customer data security responsibilities</h3>
        <p>Customers must:</p>
        <ul className="list-disc pl-5 space-y-2">
          <li>Provide required licenses for internal systems</li>
          <li>Post privacy policies complying with applicable laws</li>
          <li>Promptly notify Plivo of security breaches</li>
          <li>Appoint authorized administrators and review monthly authorization</li>
          <li>Investigate suspicious use and keep passwords confidential</li>
          <li>Not exploit known vulnerabilities</li>
          <li>Implement anti-virus protection and industry-standard security measures</li>
          <li>Notify end users of bot use prominently in privacy policies and on first interaction</li>
        </ul>

        <h3 className="font-inter text-base font-semibold text-black mt-6 mb-2">9. Customer consent for compliance analysis</h3>
        <p>Customers consent to Plivo processing, recording, and analyzing all data transmitted through services, including calls and messages, for security, fraud, and abuse prevention. Customers warrant they have obtained end-user permissions and are solely responsible for compliance with applicable laws. Customers indemnify Plivo from claims arising from data recording, monitoring, and analysis.</p>

        <h3 className="font-inter text-base font-semibold text-black mt-6 mb-2">10. Other responsibilities</h3>
        <p>Customers are responsible for all service use under their accounts, not transferring or reselling services, ensuring customer user compliance, preventing unauthorized access, addressing security incidents, cooperating with law enforcement, and not transmitting health information subject to HIPAA.</p>

        <h3 className="font-inter text-base font-semibold text-black mt-6 mb-2">11. Suspension of services</h3>
        <p>Plivo may suspend services for: violation of terms, fraudulent or abusive traffic, legal or regulatory prohibition, bankruptcy proceedings, payment default, or account balance falling below $0.00. Fees continue to accrue during suspension.</p>

        <h3 className="font-inter text-base font-semibold text-black mt-6 mb-2">12. Beta offerings</h3>
        <p>Beta offerings are for testing only and may lack functionality or contain bugs. Support terms and SLAs do not apply. Beta information is confidential.</p>

        <h3 className="font-inter text-base font-semibold text-black mt-6 mb-2">13. Emergency services disclaimer</h3>
        <p className="font-semibold text-gray-900">Services do not support emergency calls to 911 or E911. Neither Plivo nor its officers, employees, or affiliates may be held liable for any claim, damage, or loss arising from or relating to the customer&apos;s inability to use Plivo to contact any emergency services.</p>

        <h3 className="font-inter text-base font-semibold text-black mt-6 mb-2">14. POC terms</h3>
        <p>Proof of concept terms include: evaluation and testing only, no commercial services, provided &ldquo;AS-IS&rdquo; with no warranties, liability capped at $100, customer feedback may be used by Plivo, and a separate agreement is required for continued use.</p>

        <div className="mt-8 pt-6 border-t border-gray-200">
          <p className="text-xs text-gray-400">
            For the complete Services Schedule, please visit{" "}
            <a href="https://www.plivo.com/legal/services-schedule/" target="_blank" rel="noopener noreferrer" className="text-[#323dfe] hover:underline">plivo.com/legal/services-schedule</a>.
          </p>
        </div>
      </div>
    </LegalLayout>
  );
}
