// AUTO-GENERATED — do not edit manually.
// Generated by scripts/build-phone-number-pricing-cache.mjs on 2026-04-02

export interface PhoneNumberPricingNote {
  text: string;
  href?: string;
}

export interface PhoneNumberPricingRow {
  type: string;
  price: string;
  capabilities: string[];
}

export interface PhoneNumberComplianceRow {
  label: string;
  detail: string;
}

export interface PhoneNumberCalculatorData {
  local: number;
  mobile: number;
  national: number;
  shortcode: number;
  tollfree: number;
  currency: string;
}

export interface PhoneNumberPricingCountryData {
  name: string;
  regularNumbers: PhoneNumberPricingRow[];
  regularNote: PhoneNumberPricingNote | null;
  shortCodes: PhoneNumberPricingRow[];
  shortCodeNote: PhoneNumberPricingNote | null;
  compliance: PhoneNumberComplianceRow[];
  calculator: PhoneNumberCalculatorData | null;
}

export const PHONE_NUMBER_PRICING_COUNTRY_CODES = [
  "AD",
  "AE",
  "AF",
  "AG",
  "AI",
  "AL",
  "AM",
  "AN",
  "AO",
  "AR",
  "AS",
  "AT",
  "AU",
  "AW",
  "AZ",
  "BA",
  "BB",
  "BD",
  "BE",
  "BF",
  "BG",
  "BH",
  "BI",
  "BJ",
  "BL",
  "BM",
  "BN",
  "BO",
  "BR",
  "BS",
  "BT",
  "BW",
  "BY",
  "BZ",
  "CA",
  "CD",
  "CF",
  "CH",
  "CI",
  "CK",
  "CL",
  "CM",
  "CN",
  "CO",
  "CR",
  "CU",
  "CV",
  "CW",
  "CY",
  "CZ",
  "DE",
  "DJ",
  "DK",
  "DM",
  "DO",
  "DZ",
  "EC",
  "EE",
  "EG",
  "ER",
  "ES",
  "ET",
  "FI",
  "FJ",
  "FK",
  "FM",
  "FO",
  "FR",
  "GA",
  "GB",
  "GD",
  "GE",
  "GF",
  "GG",
  "GH",
  "GI",
  "GL",
  "GM",
  "GN",
  "GP",
  "GQ",
  "GR",
  "GT",
  "GU",
  "GW",
  "GY",
  "HK",
  "HN",
  "HR",
  "HT",
  "HU",
  "ID",
  "IE",
  "IL",
  "IN",
  "IQ",
  "IR",
  "IS",
  "IT",
  "JM",
  "JO",
  "JP",
  "KE",
  "KG",
  "KH",
  "KM",
  "KN",
  "KR",
  "KW",
  "KY",
  "KZ",
  "LA",
  "LB",
  "LC",
  "LI",
  "LK",
  "LR",
  "LS",
  "LT",
  "LU",
  "LV",
  "LY",
  "MA",
  "MC",
  "MD",
  "ME",
  "MF",
  "MG",
  "MH",
  "MK",
  "ML",
  "MM",
  "MN",
  "MO",
  "MP",
  "MQ",
  "MR",
  "MS",
  "MT",
  "MU",
  "MV",
  "MW",
  "MX",
  "MY",
  "MZ",
  "NA",
  "NC",
  "NE",
  "NF",
  "NG",
  "NI",
  "NL",
  "NO",
  "NP",
  "NU",
  "NZ",
  "OM",
  "PA",
  "PE",
  "PF",
  "PG",
  "PH",
  "PK",
  "PL",
  "PM",
  "PR",
  "PS",
  "PT",
  "PW",
  "PY",
  "QA",
  "RE",
  "RO",
  "RS",
  "RU",
  "RW",
  "SA",
  "SB",
  "SC",
  "SD",
  "SE",
  "SG",
  "SI",
  "SK",
  "SL",
  "SM",
  "SN",
  "SO",
  "SR",
  "SS",
  "ST",
  "SV",
  "SY",
  "SZ",
  "TC",
  "TD",
  "TG",
  "TH",
  "TJ",
  "TL",
  "TM",
  "TN",
  "TO",
  "TR",
  "TT",
  "TV",
  "TW",
  "TZ",
  "UA",
  "UG",
  "US",
  "UY",
  "UZ",
  "VC",
  "VE",
  "VG",
  "VI",
  "VN",
  "VU",
  "WS",
  "YE",
  "ZA",
  "ZM",
  "ZW"
] as const;

export const PHONE_NUMBER_PRICING_COUNTRY_NAMES: Record<string, string> = {
  "AD": "Andorra",
  "AE": "United Arab Emirates",
  "AF": "Afghanistan",
  "AG": "Antigua and Barbuda",
  "AI": "Anguilla",
  "AL": "Albania",
  "AM": "Armenia",
  "AN": "Netherlands Antilles",
  "AO": "Angola",
  "AR": "Argentina",
  "AS": "American Samoa",
  "AT": "Austria",
  "AU": "Australia",
  "AW": "Aruba",
  "AZ": "Azerbaijan",
  "BA": "Bosnia and Herzegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Belgium",
  "BF": "Burkina Faso",
  "BG": "Bulgaria",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Saint-Barthelemy",
  "BM": "Bermuda",
  "BN": "Brunei",
  "BO": "Bolivia",
  "BR": "Brazil",
  "BS": "Bahamas",
  "BT": "Bhutan",
  "BW": "Botswana",
  "BY": "Belarus",
  "BZ": "Belize",
  "CA": "Canada",
  "CD": "Congo Democratic Republic",
  "CF": "Central African Republic",
  "CH": "Switzerland",
  "CI": "Ivory Coast",
  "CK": "Cook Islands",
  "CL": "Chile",
  "CM": "Cameroon",
  "CN": "China",
  "CO": "Colombia",
  "CR": "Costa Rica",
  "CU": "Cuba",
  "CV": "Cape Verde",
  "CW": "Curaao",
  "CY": "Cyprus",
  "CZ": "Czech Republic",
  "DE": "Germany",
  "DJ": "Djibouti",
  "DK": "Denmark",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "DZ": "Algeria",
  "EC": "Ecuador",
  "EE": "Estonia",
  "EG": "Egypt",
  "ER": "Eritrea",
  "ES": "Spain",
  "ET": "Ethiopia",
  "FI": "Finland",
  "FJ": "Fiji",
  "FK": "Falkland Islands (Malvinas)",
  "FM": "Micronesia",
  "FO": "Faeroe Islands",
  "FR": "France",
  "GA": "Gabon",
  "GB": "United Kingdom",
  "GD": "Grenada",
  "GE": "Georgia",
  "GF": "French Guiana",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Greenland",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "Equatorial Guinea",
  "GR": "Greece",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea Bissau",
  "GY": "Guyana",
  "HK": "Hong Kong",
  "HN": "Honduras",
  "HR": "Croatia",
  "HT": "Haiti",
  "HU": "Hungary",
  "ID": "Indonesia",
  "IE": "Ireland",
  "IL": "Israel",
  "IN": "India",
  "IQ": "Iraq",
  "IR": "Iran",
  "IS": "Iceland",
  "IT": "Italy",
  "JM": "Jamaica",
  "JO": "Jordan",
  "JP": "Japan",
  "KE": "Kenya",
  "KG": "Kyrgyzstan",
  "KH": "Cambodia",
  "KM": "Comoros",
  "KN": "Saint Kitts And Nevis",
  "KR": "South Korea",
  "KW": "Kuwait",
  "KY": "Cayman Islands",
  "KZ": "Kazakhstan",
  "LA": "Laos",
  "LB": "Lebanon",
  "LC": "Saint Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "LV": "Latvia",
  "LY": "Libya",
  "MA": "Morocco",
  "MC": "Monaco",
  "MD": "Moldova",
  "ME": "Montenegro",
  "MF": "Saint Martin",
  "MG": "Madagascar",
  "MH": "Marshall Islands",
  "MK": "Macedonia",
  "ML": "Mali",
  "MM": "Myanmar",
  "MN": "Mongolia",
  "MO": "Macao",
  "MP": "Northern Mariana Islands",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maldives",
  "MW": "Malawi",
  "MX": "Mexico",
  "MY": "Malaysia",
  "MZ": "Mozambique",
  "NA": "Namibia",
  "NC": "New Caledonia",
  "NE": "Niger",
  "NF": "Norfolk Island",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Netherlands",
  "NO": "Norway",
  "NP": "Nepal",
  "NU": "Niue",
  "NZ": "New Zealand",
  "OM": "Oman",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "French Polynesia",
  "PG": "Papua New Guinea",
  "PH": "Philippines",
  "PK": "Pakistan",
  "PL": "Poland",
  "PM": "Saint Pierre and Miquelon",
  "PR": "Puerto Rico",
  "PS": "Palestinian Authority",
  "PT": "Portugal",
  "PW": "Palau",
  "PY": "Paraguay",
  "QA": "Qatar",
  "RE": "Reunion",
  "RO": "Romania",
  "RS": "Serbia",
  "RU": "Russia",
  "RW": "Rwanda",
  "SA": "Saudi Arabia",
  "SB": "Solomon Islands",
  "SC": "Seychelles",
  "SD": "Sudan",
  "SE": "Sweden",
  "SG": "Singapore",
  "SI": "Slovenia",
  "SK": "Slovakia",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Suriname",
  "SS": "South Sudan",
  "ST": "Sao Tome and Principe",
  "SV": "El Salvador",
  "SY": "Syria",
  "SZ": "Swaziland",
  "TC": "Turks and Caicos Islands",
  "TD": "Chad",
  "TG": "Togo",
  "TH": "Thailand",
  "TJ": "Tajikistan",
  "TL": "Timor Leste",
  "TM": "Turkmenistan",
  "TN": "Tunisia",
  "TO": "Tonga",
  "TR": "Turkey",
  "TT": "Trinidad and Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tanzania",
  "UA": "Ukraine",
  "UG": "Uganda",
  "US": "United States",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VC": "Saint Vincent and Grenadines",
  "VE": "Venezuela",
  "VG": "Virgin Islands - British",
  "VI": "Virgin Islands - United States",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "WS": "Samoa",
  "YE": "Yemen",
  "ZA": "South Africa",
  "ZM": "Zambia",
  "ZW": "Zimbabwe"
};

export const PHONE_NUMBER_PRICING_CACHE: Record<string, PhoneNumberPricingCountryData> = {
  "AD": {
    "name": "Andorra",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "AE": {
    "name": "United Arab Emirates",
    "regularNumbers": [
      {
        "type": "Toll-Free Numbers",
        "price": "$50.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [
      {
        "label": "Toll-Free Numbers",
        "detail": "Copy of Business Registration, Foreign Address, LOI"
      }
    ],
    "calculator": {
      "local": 0,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 20,
      "currency": "$"
    }
  },
  "AF": {
    "name": "Afghanistan",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "AG": {
    "name": "Antigua and Barbuda",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "AI": {
    "name": "Anguilla",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "AL": {
    "name": "Albania",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "AM": {
    "name": "Armenia",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "AN": {
    "name": "Netherlands Antilles",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "AO": {
    "name": "Angola",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "AR": {
    "name": "Argentina",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$7.50/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 7.5,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 0,
      "currency": "$"
    }
  },
  "AS": {
    "name": "American Samoa",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "AT": {
    "name": "Austria",
    "regularNumbers": [
      {
        "type": "Mobile Numbers",
        "price": "$7.00/month",
        "capabilities": [
          "Voice",
          "SMS",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$21.25/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 0,
      "mobile": 7,
      "national": 0,
      "shortcode": 0,
      "tollfree": 21.25,
      "currency": "$"
    }
  },
  "AU": {
    "name": "Australia",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$2.50/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Mobile Numbers",
        "price": "$5.00/month",
        "capabilities": [
          "Voice",
          "SMS",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$12.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [
      {
        "label": "Local Numbers",
        "detail": "Not Needed"
      },
      {
        "label": "Mobile Numbers",
        "detail": "Not Needed"
      },
      {
        "label": "Toll-Free Numbers",
        "detail": "Not Needed"
      }
    ],
    "calculator": {
      "local": 2.5,
      "mobile": 5,
      "national": 0,
      "shortcode": 0,
      "tollfree": 12,
      "currency": "$"
    }
  },
  "AW": {
    "name": "Aruba",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "AZ": {
    "name": "Azerbaijan",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "BA": {
    "name": "Bosnia and Herzegovina",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "BB": {
    "name": "Barbados",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "BD": {
    "name": "Bangladesh",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "BE": {
    "name": "Belgium",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$2.50/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Mobile Numbers",
        "price": "$1.00/month",
        "capabilities": [
          "Voice",
          "SMS",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$21.25/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 2.5,
      "mobile": 1,
      "national": 0,
      "shortcode": 0,
      "tollfree": 21.25,
      "currency": "$"
    }
  },
  "BF": {
    "name": "Burkina Faso",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "BG": {
    "name": "Bulgaria",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$2.55/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 2.55,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 0,
      "currency": "$"
    }
  },
  "BH": {
    "name": "Bahrain",
    "regularNumbers": [
      {
        "type": "Toll-Free Numbers",
        "price": "$10.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 0,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 10,
      "currency": "$"
    }
  },
  "BI": {
    "name": "Burundi",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "BJ": {
    "name": "Benin",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "BL": {
    "name": "Saint-Barthelemy",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "BM": {
    "name": "Bermuda",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "BN": {
    "name": "Brunei",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "BO": {
    "name": "Bolivia",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "BR": {
    "name": "Brazil",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$6.17/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$30.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [
      {
        "label": "Local Numbers",
        "detail": "Local address, Tax ID (CNPJ)"
      },
      {
        "label": "Toll-Free Numbers",
        "detail": "National address, Tax ID (CNPJ)"
      }
    ],
    "calculator": {
      "local": 6.17,
      "mobile": 20,
      "national": 0,
      "shortcode": 0,
      "tollfree": 30,
      "currency": "$"
    }
  },
  "BS": {
    "name": "Bahamas",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "BT": {
    "name": "Bhutan",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "BW": {
    "name": "Botswana",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "BY": {
    "name": "Belarus",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "BZ": {
    "name": "Belize",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "CA": {
    "name": "Canada",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$0.75/month",
        "capabilities": [
          "Voice",
          "SMS",
          "MMS",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$1.00/month",
        "capabilities": [
          "Voice",
          "SMS",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [
      {
        "type": "Short Code*",
        "price": "$700/month (Billed every 4 months)",
        "capabilities": [
          "SMS",
          "MMS"
        ]
      }
    ],
    "shortCodeNote": {
      "text": "*All short codes have a $4,000 one-time fee charged at the time of purchase."
    },
    "compliance": [
      {
        "label": "Local Numbers",
        "detail": "Not Needed"
      },
      {
        "label": "Toll-Free Numbers",
        "detail": "Not Needed"
      }
    ],
    "calculator": {
      "local": 0.75,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 2,
      "currency": "$"
    }
  },
  "CD": {
    "name": "Congo Democratic Republic",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "CF": {
    "name": "Central African Republic",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "CH": {
    "name": "Switzerland",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$0.85/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$21.25/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 0.85,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 21.25,
      "currency": "$"
    }
  },
  "CI": {
    "name": "Ivory Coast",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "CK": {
    "name": "Cook Islands",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "CL": {
    "name": "Chile",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$5.95/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$43.22/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 5.95,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 43.22,
      "currency": "$"
    }
  },
  "CM": {
    "name": "Cameroon",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "CN": {
    "name": "China",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$75.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$150.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 75,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 150,
      "currency": "$"
    }
  },
  "CO": {
    "name": "Colombia",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$17.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$21.25/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 17,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 21.25,
      "currency": "$"
    }
  },
  "CR": {
    "name": "Costa Rica",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "CU": {
    "name": "Cuba",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "CV": {
    "name": "Cape Verde",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "CW": {
    "name": "Curaao",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "CY": {
    "name": "Cyprus",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$30.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$11.67/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 30,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 11.67,
      "currency": "$"
    }
  },
  "CZ": {
    "name": "Czech Republic",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$1.25/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$29.75/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 1.25,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 29.75,
      "currency": "$"
    }
  },
  "DE": {
    "name": "Germany",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "DJ": {
    "name": "Djibouti",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "DK": {
    "name": "Denmark",
    "regularNumbers": [
      {
        "type": "National Numbers",
        "price": "$2.10/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$21.25/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 0,
      "mobile": 0,
      "national": 2.1,
      "shortcode": 0,
      "tollfree": 21.25,
      "currency": "$"
    }
  },
  "DM": {
    "name": "Dominica",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "DO": {
    "name": "Dominican Republic",
    "regularNumbers": [
      {
        "type": "Toll-Free Numbers",
        "price": "$46.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 0,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 46,
      "currency": "$"
    }
  },
  "DZ": {
    "name": "Algeria",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "EC": {
    "name": "Ecuador",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "EE": {
    "name": "Estonia",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "EG": {
    "name": "Egypt",
    "regularNumbers": [
      {
        "type": "Toll-Free Numbers",
        "price": "$50.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 0,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 50,
      "currency": "$"
    }
  },
  "ER": {
    "name": "Eritrea",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "ES": {
    "name": "Spain",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$3.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$21.25/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 3,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 21.25,
      "currency": "$"
    }
  },
  "ET": {
    "name": "Ethiopia",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "FI": {
    "name": "Finland",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$1.25/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$34.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 1.25,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 34,
      "currency": "$"
    }
  },
  "FJ": {
    "name": "Fiji",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "FK": {
    "name": "Falkland Islands (Malvinas)",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "FM": {
    "name": "Micronesia",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "FO": {
    "name": "Faeroe Islands",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "FR": {
    "name": "France",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$2.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Mobile Numbers",
        "price": "$2.00/month",
        "capabilities": [
          "Voice",
          "SMS",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$1.35/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 2,
      "mobile": 2,
      "national": 0,
      "shortcode": 0,
      "tollfree": 1.35,
      "currency": "$"
    }
  },
  "GA": {
    "name": "Gabon",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "GB": {
    "name": "United Kingdom",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$0.85/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Mobile Numbers",
        "price": "$0.90/month",
        "capabilities": [
          "Voice",
          "SMS",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [
      {
        "label": "Local Numbers",
        "detail": "Not Needed"
      },
      {
        "label": "Mobile Numbers",
        "detail": "Not Needed"
      }
    ],
    "calculator": {
      "local": 1.4,
      "mobile": 0.9,
      "national": 0,
      "shortcode": 0,
      "tollfree": 1,
      "currency": "$"
    }
  },
  "GD": {
    "name": "Grenada",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "GE": {
    "name": "Georgia",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "GF": {
    "name": "French Guiana",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "GG": {
    "name": "Guernsey",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "GH": {
    "name": "Ghana",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "GI": {
    "name": "Gibraltar",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "GL": {
    "name": "Greenland",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "GM": {
    "name": "Gambia",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "GN": {
    "name": "Guinea",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "GP": {
    "name": "Guadeloupe",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "GQ": {
    "name": "Equatorial Guinea",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "GR": {
    "name": "Greece",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$1.25/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$21.25/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 1.25,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 21.25,
      "currency": "$"
    }
  },
  "GT": {
    "name": "Guatemala",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "GU": {
    "name": "Guam",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "GW": {
    "name": "Guinea Bissau",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "GY": {
    "name": "Guyana",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "HK": {
    "name": "Hong Kong",
    "regularNumbers": [
      {
        "type": "Mobile Numbers",
        "price": "$25.00/month",
        "capabilities": [
          "Voice",
          "SMS",
          "SIP Trunking"
        ]
      },
      {
        "type": "National Numbers",
        "price": "$5.10/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 0,
      "mobile": 25,
      "national": 5.1,
      "shortcode": 0,
      "tollfree": 0,
      "currency": "$"
    }
  },
  "HN": {
    "name": "Honduras",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "HR": {
    "name": "Croatia",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$4.25/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$6.50/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 4.25,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 6.5,
      "currency": "$"
    }
  },
  "HT": {
    "name": "Haiti",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "HU": {
    "name": "Hungary",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$20.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$11.50/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 3.4,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 11.5,
      "currency": "$"
    }
  },
  "ID": {
    "name": "Indonesia",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$25.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 25,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 0,
      "currency": "$"
    }
  },
  "IE": {
    "name": "Ireland",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$0.85/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "National Numbers",
        "price": "$0.85/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$21.25/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 0.85,
      "mobile": 0,
      "national": 0.85,
      "shortcode": 0,
      "tollfree": 21.25,
      "currency": "$"
    }
  },
  "IL": {
    "name": "Israel",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$3.40/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$21.25/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 3.4,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 21.25,
      "currency": "$"
    }
  },
  "IN": {
    "name": "India",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "₹250.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": {
      "text": "*Rate for Domestic Calling",
      "href": "https://support.plivo.com/hc/en-us/articles/16859884362265"
    },
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [
      {
        "label": "Local Numbers",
        "detail": "Certificate of Incorporation, GST"
      }
    ],
    "calculator": {
      "local": 250,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 0,
      "currency": "₹"
    }
  },
  "IQ": {
    "name": "Iraq",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "IR": {
    "name": "Iran",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "IS": {
    "name": "Iceland",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "IT": {
    "name": "Italy",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "JM": {
    "name": "Jamaica",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "JO": {
    "name": "Jordan",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "JP": {
    "name": "Japan",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$5.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 5,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 0,
      "currency": "$"
    }
  },
  "KE": {
    "name": "Kenya",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "KG": {
    "name": "Kyrgyzstan",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "KH": {
    "name": "Cambodia",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "KM": {
    "name": "Comoros",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "KN": {
    "name": "Saint Kitts And Nevis",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "KR": {
    "name": "South Korea",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "KW": {
    "name": "Kuwait",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "KY": {
    "name": "Cayman Islands",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "KZ": {
    "name": "Kazakhstan",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "LA": {
    "name": "Laos",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "LB": {
    "name": "Lebanon",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "LC": {
    "name": "Saint Lucia",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "LI": {
    "name": "Liechtenstein",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "LK": {
    "name": "Sri Lanka",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "LR": {
    "name": "Liberia",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "LS": {
    "name": "Lesotho",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "LT": {
    "name": "Lithuania",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$1.50/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$22.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 1.5,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 22,
      "currency": "$"
    }
  },
  "LU": {
    "name": "Luxembourg",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "LV": {
    "name": "Latvia",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$1.50/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 1.5,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 0,
      "currency": "$"
    }
  },
  "LY": {
    "name": "Libya",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "MA": {
    "name": "Morocco",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "MC": {
    "name": "Monaco",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "MD": {
    "name": "Moldova",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "ME": {
    "name": "Montenegro",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "MF": {
    "name": "Saint Martin",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "MG": {
    "name": "Madagascar",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "MH": {
    "name": "Marshall Islands",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "MK": {
    "name": "Macedonia",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "ML": {
    "name": "Mali",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "MM": {
    "name": "Myanmar",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "MN": {
    "name": "Mongolia",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "MO": {
    "name": "Macao",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "MP": {
    "name": "Northern Mariana Islands",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "MQ": {
    "name": "Martinique",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "MR": {
    "name": "Mauritania",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "MS": {
    "name": "Montserrat",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "MT": {
    "name": "Malta",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "MU": {
    "name": "Mauritius",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "MV": {
    "name": "Maldives",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "MW": {
    "name": "Malawi",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "MX": {
    "name": "Mexico",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$5.83/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$25.50/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 5.83,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 25.5,
      "currency": "$"
    }
  },
  "MY": {
    "name": "Malaysia",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$18.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 18,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 0,
      "currency": "$"
    }
  },
  "MZ": {
    "name": "Mozambique",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "NA": {
    "name": "Namibia",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "NC": {
    "name": "New Caledonia",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "NE": {
    "name": "Niger",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "NF": {
    "name": "Norfolk Island",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "NG": {
    "name": "Nigeria",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "NI": {
    "name": "Nicaragua",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "NL": {
    "name": "Netherlands",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$2.55/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Mobile Numbers",
        "price": "$10.00/month",
        "capabilities": [
          "Voice",
          "SMS",
          "SIP Trunking"
        ]
      },
      {
        "type": "National Numbers",
        "price": "$2.55/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$21.25/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 2.55,
      "mobile": 10,
      "national": 2.55,
      "shortcode": 0,
      "tollfree": 21.25,
      "currency": "$"
    }
  },
  "NO": {
    "name": "Norway",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "NP": {
    "name": "Nepal",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "NU": {
    "name": "Niue",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "NZ": {
    "name": "New Zealand",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$2.55/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$34.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [
      {
        "label": "Local Numbers",
        "detail": "National address, NZBN"
      },
      {
        "label": "Toll-Free Numbers",
        "detail": "National address, NZBN"
      }
    ],
    "calculator": {
      "local": 2.55,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 34,
      "currency": "$"
    }
  },
  "OM": {
    "name": "Oman",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "PA": {
    "name": "Panama",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "PE": {
    "name": "Peru",
    "regularNumbers": [
      {
        "type": "Toll-Free Numbers",
        "price": "$43.33/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 0,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 43.33,
      "currency": "$"
    }
  },
  "PF": {
    "name": "French Polynesia",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "PG": {
    "name": "Papua New Guinea",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "PH": {
    "name": "Philippines",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$25.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$21.25/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 25,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 21.25,
      "currency": "$"
    }
  },
  "PK": {
    "name": "Pakistan",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "PL": {
    "name": "Poland",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$0.85/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Mobile Numbers",
        "price": "$11.50/month",
        "capabilities": [
          "Voice",
          "SMS",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 0.85,
      "mobile": 11.5,
      "national": 0,
      "shortcode": 0,
      "tollfree": 0,
      "currency": "$"
    }
  },
  "PM": {
    "name": "Saint Pierre and Miquelon",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "PR": {
    "name": "Puerto Rico",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "PS": {
    "name": "Palestinian Authority",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "PT": {
    "name": "Portugal",
    "regularNumbers": [
      {
        "type": "National Numbers",
        "price": "$1.25/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$21.25/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 0,
      "mobile": 0,
      "national": 1.25,
      "shortcode": 0,
      "tollfree": 21.25,
      "currency": "$"
    }
  },
  "PW": {
    "name": "Palau",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "PY": {
    "name": "Paraguay",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "QA": {
    "name": "Qatar",
    "regularNumbers": [
      {
        "type": "Toll-Free Numbers",
        "price": "$750.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 0,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 750,
      "currency": "$"
    }
  },
  "RE": {
    "name": "Reunion",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "RO": {
    "name": "Romania",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$2.55/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 2.55,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 0,
      "currency": "$"
    }
  },
  "RS": {
    "name": "Serbia",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "RU": {
    "name": "Russia",
    "regularNumbers": [
      {
        "type": "Toll-Free Numbers",
        "price": "$54.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 0,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 54,
      "currency": "$"
    }
  },
  "RW": {
    "name": "Rwanda",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "SA": {
    "name": "Saudi Arabia",
    "regularNumbers": [
      {
        "type": "Toll-Free Numbers",
        "price": "$115.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 0,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 115,
      "currency": "$"
    }
  },
  "SB": {
    "name": "Solomon Islands",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "SC": {
    "name": "Seychelles",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "SD": {
    "name": "Sudan",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "SE": {
    "name": "Sweden",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$1.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Mobile Numbers",
        "price": "$2.50/month",
        "capabilities": [
          "Voice",
          "SMS",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$10.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 1,
      "mobile": 2.5,
      "national": 0,
      "shortcode": 0,
      "tollfree": 10,
      "currency": "$"
    }
  },
  "SG": {
    "name": "Singapore",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$16.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [
      {
        "label": "Local Numbers",
        "detail": "National address, Tax ID (NRIC)"
      }
    ],
    "calculator": {
      "local": 0,
      "mobile": 0,
      "national": 16,
      "shortcode": 0,
      "tollfree": 0,
      "currency": "$"
    }
  },
  "SI": {
    "name": "Slovenia",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$4.25/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$6.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 4.25,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 6,
      "currency": "$"
    }
  },
  "SK": {
    "name": "Slovakia",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$1.50/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$21.25/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 1.5,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 21.25,
      "currency": "$"
    }
  },
  "SL": {
    "name": "Sierra Leone",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "SM": {
    "name": "San Marino",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "SN": {
    "name": "Senegal",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "SO": {
    "name": "Somalia",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "SR": {
    "name": "Suriname",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "SS": {
    "name": "South Sudan",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "ST": {
    "name": "Sao Tome and Principe",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "SV": {
    "name": "El Salvador",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "SY": {
    "name": "Syria",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "SZ": {
    "name": "Swaziland",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "TC": {
    "name": "Turks and Caicos Islands",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "TD": {
    "name": "Chad",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "TG": {
    "name": "Togo",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "TH": {
    "name": "Thailand",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "TJ": {
    "name": "Tajikistan",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "TL": {
    "name": "Timor Leste",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "TM": {
    "name": "Turkmenistan",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "TN": {
    "name": "Tunisia",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "TO": {
    "name": "Tonga",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "TR": {
    "name": "Turkey",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$45.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$85.00/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 45,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 85,
      "currency": "$"
    }
  },
  "TT": {
    "name": "Trinidad and Tobago",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "TV": {
    "name": "Tuvalu",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "TW": {
    "name": "Taiwan",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "TZ": {
    "name": "Tanzania",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "UA": {
    "name": "Ukraine",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "UG": {
    "name": "Uganda",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "US": {
    "name": "United States",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$0.50/month",
        "capabilities": [
          "Voice",
          "SMS",
          "MMS",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$1.00/month",
        "capabilities": [
          "Voice",
          "SMS",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [
      {
        "type": "Regular",
        "price": "$500/month (Billed quarterly)",
        "capabilities": [
          "SMS",
          "MMS"
        ]
      },
      {
        "type": "Vanity",
        "price": "$1,000/month (Billed quarterly)",
        "capabilities": [
          "SMS",
          "MMS"
        ]
      }
    ],
    "shortCodeNote": {
      "text": "*All short codes have a $1,500 one-time fee charged at the time of purchase."
    },
    "compliance": [
      {
        "label": "Local Numbers",
        "detail": "Not Needed"
      },
      {
        "label": "Toll-Free Numbers",
        "detail": "Not Needed"
      }
    ],
    "calculator": {
      "local": 1.8,
      "mobile": 0,
      "national": 0,
      "shortcode": 1000,
      "tollfree": 2,
      "currency": "$"
    }
  },
  "UY": {
    "name": "Uruguay",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "UZ": {
    "name": "Uzbekistan",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "VC": {
    "name": "Saint Vincent and Grenadines",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "VE": {
    "name": "Venezuela",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "VG": {
    "name": "Virgin Islands - British",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "VI": {
    "name": "Virgin Islands - United States",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "VN": {
    "name": "Vietnam",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "VU": {
    "name": "Vanuatu",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "WS": {
    "name": "Samoa",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "YE": {
    "name": "Yemen",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "ZA": {
    "name": "South Africa",
    "regularNumbers": [
      {
        "type": "Local Numbers",
        "price": "$1.28/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      },
      {
        "type": "Toll-Free Numbers",
        "price": "$7.50/month",
        "capabilities": [
          "Voice",
          "SIP Trunking"
        ]
      }
    ],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": {
      "local": 1.28,
      "mobile": 0,
      "national": 0,
      "shortcode": 0,
      "tollfree": 7.5,
      "currency": "$"
    }
  },
  "ZM": {
    "name": "Zambia",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  },
  "ZW": {
    "name": "Zimbabwe",
    "regularNumbers": [],
    "regularNote": null,
    "shortCodes": [],
    "shortCodeNote": null,
    "compliance": [],
    "calculator": null
  }
};
